### ISSUE TITLE
looker ignores files on the command line and doesn't say anything

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/looker#2]
This hung:

```
# looker $(svcs -L sled-agent)
^C
```

The file does exist:

```
# tail -1 $(svcs -L sled-agent) | looker
08:46:50.175Z WARN SledAgent: failed to notify nexus about sled agent: no record found for Query { name: Name("_nexus._tcp.control-plane.oxide.internal."), query_type: AAAA, query_class: IN }, will retry in 1.040373496s
```

I think there are a few things here:

- If looker doesn't accept files on the command line, presumably this should be a syntax error?  Unless it interpreted the file as a valid value for some other argument?
- It would be nice if it _did_ accept files on the command line
- Either way, if it's going to read from stdin and stdin is a tty, how about printing a warning message like "note: reading from stdin, which is a tty"?  I don't think this is common, but I've seen a bunch of tools do it and I don't know of any downside.

**Comment by jclulow** [comment]
I have made it a syntax error to provide positional arguments for now, because that was quick and easy.  I have also added a warning message when stdin is a tty.  I will do follow-up work to add the ability to tail either specific files or SMF logs, etc.

```
$ looker blah
Usage: looker [--help] [-C] [-N]
ERROR: unexpected arguments

$ looker
WARNING: reading from stdin, which is a tty
^C

$ looker </dev/null
```

Fixed in 3b5a9657ff418af9041925e2e178e94c7532cfc5.
