### ISSUE TITLE
print full timestamps in ISO 8601?

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/looker#8]
Currently when using `-o long`, timestamps are printed like `2023-10-26 21:50:12.008Z`.  This is almost ISO 8601 but not quite.  It should be `2023-10-26T21:50:12.008Z`.  This obviously isn't a big deal but when you're copying and pasting a lot of timestamps out of a log while debugging, it's annoying to deal with timestamps in several different formats.  Plus, you can't double-click it to select it because of the space.

**Comment by jclulow** [comment]
I find the T makes it substantially more difficult to visually locate the time, especially when I'm looking at a lot of timestamps, which is why I left it out.

Would you prefer a new output format name other than **long** (what would you pick!) or would you prefer a short flag of some kind that just says dates should always be strict ISO 8601 no matter where they appear in any format?

**Comment by davepacheco** [comment]
I'm not sure it merits a new output format.  I will update my own tooling to accept this format and see how it goes.
